version: "3.9"

services:
  todo:
    container_name: microservices-practice-todo-container
    build: ./todo_list
    image: microservices-practice-todo-image
    ports:
      - "8000:80"
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db
      - zookeeper
      - kafka
  statistics:
    container_name: microservices-practice-statistics-container
    build: ./statistics
    image: microservices-practice-statistics-image
    ports:
      - "8001:80"
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db
      - todo
      - zookeeper
      - kafka
  db:
    container_name: microservices-practice-db-container
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data
  zookeeper:
    container_name: microservices-practice-zookeeper-container
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    ports:
      - "2181:2181"
    env_file:
      - ./.env
    depends_on:
      - db
  kafka:
    container_name: microservices-practice-kafka-container
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - ./.env
    depends_on:
      - db
      - zookeeper
volumes:
  db: